# Generated by Django 3.0.4 on 2020-03-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=250)),
                ('dataNascimento', models.CharField(max_length=250)),
            ],
        ),
    ]
