# Generated by Django 3.0.4 on 2020-04-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aluno_idade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha_fisica',
            old_name='medida_antibraco',
            new_name='medida_antibraco_direito',
        ),
        migrations.RenameField(
            model_name='ficha_fisica',
            old_name='medida_biceps',
            new_name='medida_antibraco_esquerdo',
        ),
        migrations.RenameField(
            model_name='ficha_fisica',
            old_name='medida_coxa',
            new_name='medida_biceps_direito',
        ),
        migrations.RenameField(
            model_name='ficha_fisica',
            old_name='medida_panturrilha',
            new_name='medida_biceps_esquerdo',
        ),
        migrations.RenameField(
            model_name='ficha_fisica',
            old_name='medida_tricpes',
            new_name='medida_coxa_direita',
        ),
        migrations.AddField(
            model_name='ficha_fisica',
            name='medida_coxa_esquerda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ficha_fisica',
            name='medida_panturrilha_direita',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ficha_fisica',
            name='medida_panturrilha_esquerda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ficha_fisica',
            name='medida_tricpes_direito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ficha_fisica',
            name='medida_tricpes_esquerdo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
