# Generated by Django 3.0.4 on 2020-05-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200430_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha_fisica',
            old_name='medida_abdome',
            new_name='medida_abdomen',
        ),
        migrations.RenameField(
            model_name='ficha_fisica',
            old_name='medida_antibraco_direito',
            new_name='medida_altura',
        ),
        migrations.RenameField(
            model_name='ficha_fisica',
            old_name='medida_antibraco_esquerdo',
            new_name='medida_antebraco_direito',
        ),
        migrations.RenameField(
            model_name='ficha_fisica',
            old_name='medida_tricpes_direito',
            new_name='medida_antebraco_esquerdo',
        ),
        migrations.RenameField(
            model_name='ficha_fisica',
            old_name='medida_tricpes_esquerdo',
            new_name='medida_triceps_direito',
        ),
        migrations.AddField(
            model_name='ficha_fisica',
            name='medida_triceps_esquerdo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
