# Generated by Django 3.0.4 on 2020-04-06 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ficha_fisica'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha_fisica',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha_fisica',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
