# Generated by Django 3.0.4 on 2020-04-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ficha_fisica_percentual_gordura'),
        ('app', '0004_auto_20200406_1257'),
    ]

    operations = [
    ]
