# Generated by Django 2.1.7 on 2020-04-13 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200412_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
