# Generated by Django 2.1.7 on 2020-04-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_aluno_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'M'), ('feminino', 'F')], max_length=1),
        ),
    ]
