# Generated by Django 2.1.7 on 2020-04-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200414_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'M'), ('feminino', 'F')], default='M', max_length=1),
        ),
    ]
