# Generated by Django 2.1.7 on 2020-04-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200414_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('masc', 'M'), ('fem', 'F')], default='masc', max_length=1),
        ),
    ]
