# Generated by Django 2.1.7 on 2020-04-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200414_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('', '')], default='', max_length=1),
        ),
    ]
